module.exports = {
  User: require("./user"),
  Pet: require("./pet"),
  Post: require("./post"),
  PostComment: require("./postComment"),
  PostLike: require("./postLike"),
  UserFeed: require("./userFeed"),
  UserFollower: require("./userFollower"),
  PaymentMethod: require("./paymentMethod"),
  BankDetails: require("./bankDetails"),
  Description: require("./description"),
  Animal: require("./animal"),
  Organization: require("./organization"),
  Characteristic: require("./characteristic"),
};
